#!/bin/sh -e
wc -l `find . -name '*?pp' -o -name '*.py' -o -name '*.pyx' -o -name '*.pxd' -o -name '*.rc' -o -name '*.txt' -o -name '*.xsd' -o -name '*.xml' -o -name '*.rst' -o -name '*.java' | grep -vi cmake | egrep -v '^\./test/' | grep -v '/build/' | grep -v '/old/' | grep -v '/off/' | grep -v 'boost/preprocessor' ` | sort -n
