#!/bin/sh -e

list()
{
    find . \
        -name '*.?pp' -o \
        -name '*.h' -o \
        -name '*.c' -o \
        -name '*.py' -o \
        -name '*.pyx' -o \
        -name '*.pxd' -o \
        -name '*.rc' -o \
        -name '*.txt' -o \
        -name '*.xsd' -o \
        -name '*.xml' -o \
        -name '*.rst' -o \
        -name '*.java' -o \
        -name '*.tmpl' -o \
        -name '*.go'
}

filter()
{
    grep -vi cmake |
        egrep -v '^\./test/' |
        grep -v '/build/' |
        grep -v '/old/' |
        grep -v '/off/' |
        grep -v 'boost/preprocessor'
}

wc -l $(list | filter) | sort -n
